"""
Project Refiner Template (Blueprint for LLM/Agent Generation)
==============================================================
This template defines how project-specific refinement scripts are structured.
After Stage 1 (image analysis) produces the design specification, the AI Agent/LLM
creates 'projects/<project>/scripts/refine_<name>.py' following this pattern.

Usage in Pipeline:
  python -m harness run <project> --stage refine
"""

import os
import sys
import json
from typing import Dict, Any, List

from harness.refiners.base_refiner import BaseRefinementEngine
from harness.blender.client import send_blender_code


class ProjectRefinementEngine(BaseRefinementEngine):
    """
    Project-specific refiner generated by the LLM after Stage 1 analysis.
    Implements apply_adjustments() to translate comparison recommendations
    into targeted Blender bpy operations for this specific 3D model.
    """

    def apply_adjustments(self, pass_num: int, recommendations: List[Dict[str, Any]]) -> bool:
        """
        Applies targeted adjustments to specific Blender objects and materials
        based on the recommendations emitted by Stage 3 (comparison).

        Criteria for LLM generation:
        1. Parse recommendations emitted by Stage 3 (comparison_report.json).
        2. Map recommendation parameters to your project's specific Blender objects/materials.
        3. Formulate concise, self-contained Python bpy snippets.
        4. Send code to Blender via send_blender_code(bpy_code).
        5. Return True if adjustments were made, False if none needed.
        """
        if not recommendations:
            print(f"[Refine Pass {pass_num}] No corrective recommendations found.")
            return False

        bpy_adjustments = []

        for rec in recommendations:
            param = rec.get("parameter", "")
            action = rec.get("action", "")

            # --- Pattern 1: Geometry Transform Adjustments ---
            # e.g. If parameter relates to scale or dimension:
            if "scale" in param:
                # obj_name = "<YourProjectObjectName>"
                # target_delta = rec.get("target_delta", 0.0)
                # bpy_adjustments.append(f"""
# obj = bpy.data.objects.get('{obj_name}')
# if obj:
#     obj.scale.x = max(0.1, obj.scale.x + {target_delta})
#     obj.scale.y = max(0.1, obj.scale.y + {target_delta})
# """)
                pass

            # --- Pattern 2: Material & Principled BSDF Color Adjustments ---
            # e.g. If parameter relates to base color or roughness:
            if "color" in param:
                target_rgb = rec.get("target")
                if target_rgb and len(target_rgb) == 3:
                    # mat_name = "<YourProjectMaterialName>"
                    # bpy_adjustments.append(f"""
# mat = bpy.data.materials.get('{mat_name}')
# if mat and mat.use_nodes:
#     bsdf = mat.node_tree.nodes.get("Principled BSDF")
#     if bsdf:
#         bsdf.inputs["Base Color"].default_value = ({target_rgb[0]}, {target_rgb[1]}, {target_rgb[2]}, 1.0)
# """)
                    pass

        if bpy_adjustments:
            bpy_code = "import bpy\n" + "\n".join(bpy_adjustments)
            res = send_blender_code(bpy_code)
            return True

        return False


def main():
    geom_json = os.environ.get("HARNESS_GEOM_JSON")
    color_json = os.environ.get("HARNESS_COLOR_JSON")
    reports_dir = os.environ.get("HARNESS_REPORTS_DIR", "outputs/reports")
    renders_dir = os.environ.get("HARNESS_RENDER_DIR", "outputs/renders")
    max_iter = int(os.environ.get("HARNESS_MAX_ITERATIONS", "6"))
    target_score = float(os.environ.get("HARNESS_CONVERGENCE_THRESHOLD", "85.0"))

    engine = ProjectRefinementEngine(
        geom_json_path=geom_json,
        color_json_path=color_json,
        reports_dir=reports_dir,
        renders_dir=renders_dir,
        max_iterations=max_iter,
        target_score=target_score
    )
    result = engine.run_loop()
    print(f"[Refine] Finished with converged={result['converged']}, final_score={result['final_score']}")


if __name__ == "__main__":
    main()
